[[plugins]]
repo='vim-airline/vim-airline'

[[plugins]]
repo='vim-airline/vim-airline-themes'

[[plugins]]
repo='Yggdroot/indentLine'

[[plugins]]
repo='godlygeek/tabular'

[[plugins]]
repo='plasticboy/vim-markdown'

[[plugins]]
repo='preservim/nerdtree'

[[plugins]]
repo='Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo='jistr/vim-nerdtree-tabs'

[[plugins]]
repo='junegunn/vim-easy-align'

[[plugins]]
repo='tpope/vim-surround'

[[plugins]]
repo='ctrlpvim/ctrlp.vim'

[[plugins]]
repo='easymotion/vim-easymotion'

[[plugins]]
repo='justinmk/vim-sneak'

[[plugins]]
repo='rking/ag.vim'

[[plugins]]
repo='preservim/tagbar'

[[plugins]]
repo='sgur/ctrlp-extensions.vim'

[[plugins]]
repo='mhinz/vim-startify'

[[plugins]]
repo='neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo='tpope/vim-commentary'

[[plugins]]
repo='mattn/emmet-vim'

[[plugins]]
repo='honza/vim-snippets'

